### ISSUE TITLE
Project bootstrapping

### ISSUE THREAD

**Issue by janbuchar** [apify/crawlee-python#215]
- [ ] add a templates directory with cookiecutter projects - https://cookiecutter.readthedocs.io/en/stable/advanced/directories.html
- [ ] make a simple CLI so that `pipx run crawlee create [--template some-template-name] project-dir/` works
  - [ ] the CLI should be just a simple wrapper around `cookiecutter` that always uses the current master (for fetching templates)
  - [ ] it could be beneficial to use `inquirer`
  - available templates should be
    - [ ] ??? simple playwright project
    - [ ] ??? simple beautifulsoup project

**Comment by B4nan** [comment]
>  make a simple CLI so that pipx crawlee --template some-template-name project-dir/ works

Ideally it would be `pipx crawlee create project-dir`, `--template` arg should be optional, if not provided the inquirer should ask the user to pick one of the existing templates (same if the provided template is non-existent).

> available templates should be

Let's start with those two, I would like to see "project templates" as we have in the JS version, so with a basic setup of scraper that dynamically goes though the crawlee.dev:

https://github.com/apify/crawlee/tree/master/packages/templates/templates/cheerio-ts
https://github.com/apify/crawlee/tree/master/packages/templates/templates/playwright-ts
