### ISSUE TITLE
Crawlee for Python: Early adopters giveaway 🎁 

### ISSUE THREAD

**Issue by souravjain540** [apify/crawlee-python#269]
We just launched Crawlee for Python, and as it is in its early stages, we are looking for feedback and your contributions! 👀 

To the first 10 developers who give us relevant feedback or contribute to `crawlee-python`, we will reward them with an exclusive Crawlee Python Merch (The first 10 ever). 🎉 

![image](https://github.com/apify/crawlee-python/assets/53312820/871c26a5-5d30-435b-bfb6-12e35ff0cc95)

Terms and Conditions:

- Issues created on crawlee-python repository that add value to the library. Issues that are proper feedback for the library and improve it.
- Pull requests that add features or fix important bugs in the library.
- Feature requests that aim to improve the roadmap and future of the library.
- We won't reward typo fixes, reports, or anything similar in this campaign. 
- This campaign is on first-come-first-serve basis.
- Only issues, PRs, and feature requests accepted by the Apify team will be considered valid feedback for reward.
- The merchandise can be one or more of the following: a Crawlee for Python-branded water bottle, T-shirt, Sticker sheet, etc.
- [Join our discord](https://apify.com/discord/) for more questions.

**Comment by codejunction** [comment]
Selenium webdriver and remote driver support
https://github.com/apify/crawlee-python/issues/284

**Comment by Koppom94** [comment]
[[]()]()
