### ISSUE TITLE
pipx fails to run crawlee

### ISSUE THREAD

**Issue by siddiqkaithodu** [apify/crawlee-python#285]
When I try to ```pipx run crawlee create my-crawler```.  I get the following error

I have already installed Crawlee and its visible in the ```pip list```

```

⚠️  crawlee is already on your PATH and installed at /home/Soider/Projects/Crawlee/Crawlee/.venv/bin/crawlee. Downloading and running anyway.
'crawlee' executable script not found in package 'crawlee'.
Available executable scripts:
```

**Comment by B4nan** [comment]
Can you try `pipx run crawlee==0.1.0 create my-crawler`?

**Comment by vdusek** [comment]
Also, if you have `crawlee` already installed, you can execute the CLI directly (not via `pipx`):

```sh
$ crawlee create
```

**Comment by siddiqkaithodu** [comment]
Yes . It is working .. @B4nan 



also  `crawlee create mycrawler`  did the best


Confused with the documentation though

**Comment by siddiqkaithodu** [comment]
I think it is best to completely avoid `pipx run` for the sake of laziness :)  @vdusek
