### ISSUE TITLE
Add new HTTP client `curl-cffi`

### ISSUE THREAD

**Issue by siddiqkaithodu** [apify/crawlee-python#292]
Since we use [HTTPX](https://pypi.org/project/httpx/) , Isn't better to use [curl_cffi](https://pypi.org/project/curl-cffi/) instead or use it an optional client that switches when the HTTPX gets defeated in the AntiBot war.

I am thinking about intelligently switching between multiple http clients. (The same as of proxy rotation)

**Comment by vdusek** [comment]
Hi, thanks for the issue. I think we can split this one into two parts. First, we can (probably, needs further investigation) switch from `httpx` to `curl_cffi`, which seems better meet our use-case. The second part would be providing the end user an option to specify the HTTP client.
