### ISSUE TITLE
Automatically install dependencies after bootstrapping a project via CLI

### ISSUE THREAD

**Issue by janbuchar** [apify/crawlee-python#317]
Currently we only support poetry, but it'd be beneficial to also have a "raw pip" flavor of the templates.

**Comment by vdusek** [comment]
Could you add pip/poetry versions of the templates as part of this issue as well?

**Comment by souravjain540** [comment]
a BIG THANKS for this!

**Comment by janbuchar** [comment]
> a BIG THANKS for this!

I mean, it is on the roadmap, but not yet finished by any means. Just to make it clear.

I understand you get a lot of questions about this, huh?

**Comment by janbuchar** [comment]
See:

- https://cookiecutter.readthedocs.io/en/2.6.0/advanced/hooks.html
- https://cookiecutter.readthedocs.io/en/2.6.0/advanced/templates.html
