### ISSUE TITLE
Code Assist AI to build scrappers with Crawlee 

### ISSUE THREAD

**Issue by samyakkkk** [apify/crawlee-python#327]
Dear maintainers, greetings from [CommandDash](https://commanddash.io)! 

We are a tool to turn docs and examples of your library into a code generation AI agent which **helps devs directly generate code for your library as per their requirements.**

Our team came across Crawlee scrapper library and figured it could be helpful for new developers building on it to have one such agent. It's ready and is accessible on: [Web](https://app.commanddash.io/agent?github=https://github.com/apify/crawlee-python) (Try here!) | [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=WelltestedAI.fluttergpt) 

You can link this in your readme as a badge:

<a href="https://app.commanddash.io/agent?github=https://github.com/apify/crawlee-python"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA?style=for-the-badge"></a>
```md
<a href="https://app.commanddash.io/agent?github=https://github.com/apify/crawlee-python"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA"></a>
```
Please feel free to mention it if you believe this could be helpful for new users. Or, close the issue if not. 🙏🏻

_The agent is free to use, fully safe (no data retained) and auto-refreshes to stay upto date._

Best wishes!

**Comment by janbuchar** [comment]
Hello and kudos for CommandDash, it looks super interesting! However, we do not want to promote 3rd parties in our repository, so I have to close the issue.
