### ISSUE TITLE
add support for Parsel

### ISSUE THREAD

**Issue by Ehsan-U** [apify/crawlee-python#335]
`BeautifulSoup` lacks proper type hints, mostly `Any` type, hence not effective IDE autocompletion. A solid alternative is [Parsel](https://github.com/scrapy/parsel). It supports CSS selectors, XPath expressions for HTML and XML, JMESPath for JSON documents, and Regex expressions. Additionally, `Parsel` is the parser used by `Scrapy`.

**Comment by siddiqkaithodu** [comment]
I was thinking about [selectolax](https://pypi.org/project/selectolax/)

**Comment by Ehsan-U** [comment]
Selectolax doesn't support XPATH selector nor JMESPath for JSON.

**Comment by asymness** [comment]
+1 for Parsel

**Comment by asymness** [comment]
@janbuchar, I'd like to help out by adding Parsel support as a new crawler type. Would you be open to a PR from me for this?

**Comment by janbuchar** [comment]
> @janbuchar, I'd like to help out by adding Parsel support as a new crawler type. Would you be open to a PR from me for this?

Absolutely :slightly_smiling_face:
