### ISSUE TITLE
Chained Requests

### ISSUE THREAD

**Issue by Ehsan-U** [apify/crawlee-python#336]
How `Crawlee` can be used when requests needs to be sent in sequence like in most `ASP.Net` applications. `Scrapy` handle these cases using inline requests without CALLBACK.

e.g 
here couple of sequenced requests needs to be done to get the desired.
![image](https://github.com/user-attachments/assets/2da3eee4-411f-4f46-982e-23fd4ff76c29)

**Comment by janbuchar** [comment]
Hello, and thank you for your interest in Crawlee! I assume (correct me if I'm wrong) that you need to perform additional HTTP requests on each page you visit. Would the `send_request` helper work for you? 

```py
@crawler.router.default_handler
async def handler(context: BeautifulSoupCrawlingContext) -> None:
  response = await context.send_request(url="/foo", method="post")
  
  # parse JSON
  response_json = json.loads(response.read()) 
  
  # ...or HTML
  response_soup = BeautifulSoup(response.read())
```

**Comment by Ehsan-U** [comment]
Thanks.
`BasicCrawlingContext` doesn't give access to response so the proposed solution will only work with extended class like `BeautifulSoupCrawlingContext`

New to crawlee, correct me if I'm wrong.

**Comment by janbuchar** [comment]
You can actually do this with `BasicCrawlingContext` as well, it also provides the `send_request` helper, and the response is returned from that. Do not confuse this with `context.http_response` which is the response for the original request URL, fetched before the `request_handler` was invoked.

**Comment by janbuchar** [comment]
@Ehsan-U is your question answered? If so, please close the issue :slightly_smiling_face:
