### ISSUE TITLE
add_request does not support the label argument

### ISSUE THREAD

**Issue by MrTyton** [apify/crawlee-python#347]
The "Add Requests" does not support the label argument, so doing things like stated in the [refactoring](https://crawlee.dev/python/docs/introduction/refactoring) introduction is not possible if you have to use information from the site in order to generate links, rather than them being present already on the page.

For example, if I use a regex to pull out a bunch of hashes that are on a page, and then use those hashes to construct another URL and want to scrape that, it is not possible to do it with the enqueue_links, since that only works for links that are present on the page, and you cannot add a label to it with add_requests, so all of the splitting logic for them has to be in the `@crawler.router.default_handler` function.

**Comment by MrTyton** [comment]
I'm going to +1 on the documentation, because the current introduction doesn't really explain the difference between the two of them. The examples should likely include an example of implementing them both with the enqueue and with the add_request, since they're treated sort of interchangeable on the onboarding.

Your snippet worked, thanks for the fast response. Going to close. I'll likely come up with some more things after I mess around with this more and will offer suggestions then.

**Comment by janbuchar** [comment]
Perfect, your messing around means the world to us :slightly_smiling_face: Thanks!
