### ISSUE TITLE
Add support for `preNavigationHooks` in Playwright

### ISSUE THREAD

**Issue by viewv** [apify/crawlee-python#427]
As the title, I want to know does the crawlee-python support the `preNavigationHooks` function?

**Comment by janbuchar** [comment]
Hello and thanks for your interest in Crawlee for Python! Pre-navigation hooks are not currently supported. Before we implement this, would putting the hook code into the request handler help? Or do you need to do something before the page is loaded?

**Comment by viewv** [comment]
> Hello and thanks for your interest in Crawlee for Python! Pre-navigation hooks are not currently supported. Before we implement this, would putting the hook code into the request handler help? Or do you need to do something before the page is loaded?

OK, thank you, I want to change some browser properties before the page loaded, so I think it will be really helpful to support  the `preNavigationHooks`.

**Comment by Tallone** [comment]
I want to do something before the page loads, such as aborting when loading some images or CSS, Is there any trick available to achieve this as of now?

**Comment by vdusek** [comment]
Implementation from Crawlee JS:
- [preNavigationHooks](https://crawlee.dev/api/playwright-crawler/interface/PlaywrightCrawlerOptions#preNavigationHooks)
- [postNavigationHooks](https://crawlee.dev/api/playwright-crawler/interface/PlaywrightCrawlerOptions#postNavigationHooks)

**Comment by Yashwanth-Chandrakumar** [comment]
@vdusek /assign

**Comment by janbuchar** [comment]
> @vdusek /assign

We don't assign issues for hacktoberfest. If you want to contribute, open a PR whenever you're ready. First mergeable one gets merged.

**Comment by Yashwanth-Chandrakumar** [comment]
@janbuchar Thank Mate

**Comment by Yashwanth-Chandrakumar** [comment]
@janbuchar i have created a PR to solve the issue please view it #602
