### ISSUE TITLE
Improve error handling in `Dataset._get_data_internal()`

### ISSUE THREAD

**Issue by vdusek** [apify/crawlee-python#455]
Simulate this error in Python and handle it accordingly.

```js
    try {
        return await this.client.listItems(options);
    } catch (e) {
        const error = e as Error;
        if (error.message.includes('Cannot create a string longer than')) {
            throw new Error('dataset.getData(): The response is too large for parsing. You can fix this by lowering the "limit" option.');
        }
        throw e;
    }
```

See: https://github.com/apify/crawlee-python/blob/v0.4.0/src/crawlee/storages/_dataset.py#L272:L286

**Comment by vdusek** [comment]
@Mantisus

**Comment by Mantisus** [comment]
As I understand the handler used in the JS implementation is related to the existing line length limit in Node.js

In Python, there is no real line limit to reproduce this behavior. If the string is really big, it could trigger a MemoryError, but probably at that case the application would already crash.

**Comment by vdusek** [comment]
Thanks for the investigation. IMO in that case, you can just open a PR removing the comments and closing this issue, thanks.
