### ISSUE TITLE
Implement max crawl depth

### ISSUE THREAD

**Issue by vdusek** [apify/crawlee-python#460]
- Implement "max crawl depth" / "crawling depth limit"
- See https://github.com/apify/crawlee-python/discussions/441
- The depth information should be stored in the `Request` (`user_data` -> `crawlee_data`)

**Comment by janbuchar** [comment]
We should also make an issue in JS crawlee as well. Or am I missing a way to limit crawl depth in JS?

**Comment by vdusek** [comment]
> We should also make an issue in JS crawlee as well. Or am I missing a way to limit crawl depth in JS?

AFAIK there is no such option.

**Comment by 29deepanshutyagi** [comment]
i want to work on this issue ,kindly assign me @B4nan ,

**Comment by 29deepanshutyagi** [comment]
.take
