### ISSUE TITLE
Improve changelog formatting

### ISSUE THREAD

**Issue by B4nan** [apify/crawlee-python#468]
Currently, we format the changelog to have fully qualified links to GH issues/PRs/users, but the GH release notes don't understand this properly and no longer render the user icons or the list of contributors.

![image](https://github.com/user-attachments/assets/4ce966ae-e3fb-43f5-8ed4-94af93b80fc3)

vs

![image](https://github.com/user-attachments/assets/c5a597d3-e98e-46d2-85ab-ca2cd1cbb83b)

More info: https://apify.slack.com/archives/C06ENBV1B9Q/p1724757924089819

**Comment by ovindu-a** [comment]
Hi @B4nan, I would like to work on this.

**Comment by jaiakash** [comment]
Hi @B4nan, I would like to work on this. @ovindu-a, if you agree, can we both collaborate on this issue?
Let me know if you have created a fork for this issue...
Thanks.

**Comment by Telomelonia** [comment]
@ovindu-a @jaiakash are you still working on this?

**Comment by abhi-raval-1910** [comment]
@B4nan I would love to work on this issue and make the documentation batter

**Comment by vdusek** [comment]
@abhi-raval-1910 We don't assign issues for Hacktoberfest. If you want to work on this, open a PR. The first mergeable one gets merged.

**Comment by abhi-raval-1910** [comment]
@vdusek no prob ,I wanna contribute thats it

**Comment by janbuchar** [comment]
Just to be transparent, I'm currently working on a reusable release-metadata github action and these changes will need to be ported over to that if you make them before I'm done.

**Comment by Telomelonia** [comment]
#592 solves this

**Comment by 000xs** [comment]
Hello @B4nan ,I would like to work on this 😁

**Comment by Telomelonia** [comment]
@000xs If you want, you can commit to this PR #592.
