### ISSUE TITLE
Check CI status on `master` branch in release workflow

### ISSUE THREAD

**Issue by janbuchar** [apify/crawlee-python#469]
More details in https://github.com/apify/crawlee-python/pull/466#issuecomment-2312331905

**Comment by vdusek** [comment]
We should also publish a new version of documentation after release (and updated changelog).

**Comment by janbuchar** [comment]
I managed to do this in https://github.com/apify/apify-client-js/pull/596 (https://github.com/apify/apify-client-js/actions/runs/11478924622), what do you think @B4nan @vdusek?

**Comment by vdusek** [comment]
How does it work exactly? Does it verify if the "code checks" for the current commit are already passing, and if they are, it proceeds? If they are not, does it trigger them ?

**Comment by janbuchar** [comment]
> How does it work exactly? Does it verify if the "code checks" for the current commit are already passing, and if they are, it proceeds? If they are not, does it trigger them ?

The checks are triggerred from a separate workflow that is started on push to master. The action periodically inspects them, fails if one of them fails, succeeds if they all succeed, and keeps waiting if they are not finished. Triggering the checks from the release workflow should not be necessary.

**Comment by vdusek** [comment]
Thanks. It looks great then.
