### ISSUE TITLE
Create a new guide for scaling the crawlers

### ISSUE THREAD

**Issue by vdusek** [apify/crawlee-python#476]
- We could create a new documentation guide for scaling the crawlers (mainly the features from `_autoscaling` subpackage).
- The guide should include the following:
  - `ConcurrencySettings` - how users can configure the concurrency of requests.
  - Add a short explanation of the internal components:
    - `Snapshotter`,
    - `AutoscaledPool`.
- Inspiration: https://crawlee.dev/docs/guides/scaling-crawlers 
- How to name it? I used "request scaling" here, but it is not precise enough.

**Comment by B4nan** [comment]
why a different name? also, you scale the crawler to be able to run more requests, you don't scale the requests, right?

i would rather have a python version of the very same page instead of a different page

**Comment by vdusek** [comment]
> why a different name? also, you scale the crawler to be able to run more requests, you don't scale the requests, right?
> i would rather have a python version of the very same page instead of a different page

Yeah... I created the issue at first without looking into JS Crawlee docs, then updated it with the inspiration bullet, but not updating the title & description. I will use the same naming.

**Comment by ovindu-a** [comment]
Hi, I would like to work on this @B4nan @vdusek

**Comment by SPIDEYGUY1617** [comment]
Can you assign this issue to me ?

**Comment by vdusek** [comment]
> Hi, I would like to work on this @B4nan @vdusek

We don't assign issues for hacktoberfest. If you want to work on this, open a PR. First mergeable one gets merged.

**Comment by ovindu-a** [comment]
Noted @vdusek, thanks
