### ISSUE TITLE
Create a new guide for result storages (`Dataset`, `KeyValueStore`)

### ISSUE THREAD

**Issue by vdusek** [apify/crawlee-python#479]
- We should create a new documentation guide on how to work with result storages (`Dataset`, `KeyValueStore`).
- Inspiration: https://crawlee.dev/docs/guides/result-storage
- Check the structure of other guides - [docs/guides](https://github.com/apify/crawlee-python/tree/master/docs/guides), and try to render it using `make run-doc`.

**Comment by MostlyKIGuess** [comment]
I want to work on this, @B4nan  @souravjain540 .  Assign me if it's still open, I want to work on #481  and this together, it will be convenient.

**Comment by Atharva1723** [comment]
Can I work on this issue?

**Comment by janbuchar** [comment]
> Can I work on this issue?

Yes, feel free to open a PR whenever you're ready.

**Comment by saymedgm** [comment]
we need to add this to readme.md ?

**Comment by janbuchar** [comment]
> we need to add this to readme.md ?

No, we want it added to the `docs/` folder so that it appears in the documentation website.

**Comment by vdusek** [comment]
Check out the structure of other guides at https://github.com/apify/crawlee-python/tree/master/docs/guides.

**Comment by saymedgm** [comment]
done i have raised pr

**Comment by Manish-k723** [comment]
pls /assign , I am working on this.

**Comment by MostlyKIGuess** [comment]
> pls /assign , I am working on this.
https://github.com/apify/crawlee-python/pull/585
this PR has already been raised
