### ISSUE TITLE
Cannot use CSS on a Selector of type 'json' ( ParselCrawler )

### ISSUE THREAD

**Issue by Ehsan-U** [apify/crawlee-python#488]
Getting this error when using ParselCrawler.
`ValueError: Cannot use css on a Selector of type 'json'
`

### Reproduce:
**main.py**
```python
import asyncio

from crawlee.parsel_crawler import ParselCrawler

from crawler.routes import router


async def main() -> None:
    """The crawler entry point."""
    crawler = ParselCrawler(
        request_handler=router,
        max_requests_per_crawl=50,
    )

    await crawler.run(
        [
            'https://httpbin.org/ip',
        ]
    )


if __name__ == '__main__':
    asyncio.run(main())
```

**routes.py**
```python
from crawlee.parsel_crawler import ParselCrawlingContext
from crawlee.router import Router

router = Router[ParselCrawlingContext]()


@router.default_handler
async def default_handler(context: ParselCrawlingContext) -> None:
    """Default request handler."""
    print("hello")
```

**Comment by Ehsan-U** [comment]
The URL returns a JSON response, maybe thats causing the error.

**Comment by vdusek** [comment]
Hi @Ehsan-U, it looks like you’re trying to use an HTML (XML) parser to parse a JSON response, which won’t work (both `Parsel` and `BeautifulSoup` are HTML parsers) . If you’re working with an endpoint that returns JSON, consider using [`HttpCrawler`](https://crawlee.dev/python/api/class/HttpCrawler) and handling the response with a JSON parser, such as Python’s built-in [json](https://docs.python.org/3/library/json.html) module. 

We might also consider enhancing the error handling in `ParselCrawler` and `BeautifulSoupCrawler` to provide a more user-friendly message in such cases.
