### ISSUE TITLE
Clear storage cache automatically or make it possible

### ISSUE THREAD

**Issue by tlinhart** [apify/crawlee-python#541]
Consider this sample program:

```python
import asyncio

from crawlee.configuration import Configuration
from crawlee.parsel_crawler import ParselCrawler, ParselCrawlingContext


async def default_handler(context: ParselCrawlingContext) -> None:
    context.log.info("Inside default handler")
    for category in context.selector.xpath(
        '//div[@class="side_categories"]//ul/li/ul/li/a'
    ):
        await context.push_data({"category": category.xpath("normalize-space()").get()})


async def main() -> None:
    config = Configuration.get_global_configuration()
    config.persist_storage = False
    config.write_metadata = False
    crawler = ParselCrawler(request_handler=default_handler)
    await crawler.run(["https://books.toscrape.com"])
    data = await crawler.get_data()
    print(f"Scraped {len(data.items)} items")


if __name__ == "__main__":
    asyncio.run(main())
    asyncio.run(main())
```

It runs the same crawler two times, there's no explicit global state in the program. The first time it actually scrapes the site as can be seen in the logs / console output:

```
...
[crawlee.parsel_crawler._parsel_crawler] INFO  Inside default handler
...
```

However, the second time the crawler runs it doesn't scrape the site and hit the default handler (no `Inside default handler` log event). Setting the log level to `DEBUG`, I can see this for the second run:

```
[crawlee.storages._request_queue] DEBUG Added 1 requests to the queue, response: processed_requests=[ProcessedRequest(id='Yz6EdnZjourZ4C8', unique_key='https://books.toscrape.com', was_already_present=True, was_already_handled=True)] unprocessed_requests=[]
```

Seems like it's reusing the cache on the second run which contains the request marked as already handled.

While this behavior might be useful in some cases, there are other cases and environments when it's undesirable. One such example (and the one I actually struggle with) is running on AWS Lambda where the global state might be reused between function runs. It the function is cold started it everything works as expected. When I re-run the Lambda shortly after the previous run, the execution environment gets reused and I observe the described behavior. To get fresh data I have to make the function cold start (e.g. re-deploy the function) which is undesirable.

**Comment by janbuchar** [comment]
This seems related to https://github.com/apify/crawlee-python/issues/369

**Comment by tlinhart** [comment]
Ah yeah, I don't understand how I could miss that one... Sounds as the same problem. I tried all these kind of things mentioned there, i.e. explicitly deleting the storage directory before the run, clearing global cache structures in https://github.com/apify/crawlee-python/blob/master/src/crawlee/storages/_creation_management.py etc. Nothing worked...

Should I close this one in favour of the #369?
