### ISSUE TITLE
Include whitelisted HTTP headers in the `extended_unique_key` computation

### ISSUE THREAD

**Issue by vdusek** [apify/crawlee-python#548]
- Modify the `extended_unique_key` computation to include a set of predefined HTTP headers, alongside the existing normalized URL and payload.
- Only include headers from the whitelist.
- Identify which headers should be included, such as `Accept`, `Accept-Language`, `Authorization`, and others that may affect request outcomes.
- See the issue #178 for further context.

**Comment by ravi-hash** [comment]
Hey will you assign this issue to me

**Comment by vdusek** [comment]
Hi @ravi-hash, sure, thanks for your interest in Crawlee.
