### ISSUE TITLE
Crawlee for Python Hacktoberfest 2024 🧡 🐍 

### ISSUE THREAD

**Issue by souravjain540** [apify/crawlee-python#555]
# Crawlee for Python Hacktoberfest 2024 [Starting Oct 1, 2024]
![Hacktober 2024 Crawlee](https://github.com/user-attachments/assets/03e4c145-cf22-4618-b27f-8d434f9dd3f5)

# Prizes 🏆 

- 1-2 Accepted Pull Request: Crawlee Exclusive Sticker Sheet.
- 2 or more Accepted Pull Requests: Crawlee Exclusive Hoodie.

# Valid Issues.

- The only valid issues are with the tag `hacktoberfest`.
- Only issues in `crawlee-python` repository are valid.
- You can visit this [link](https://github.com/apify/crawlee-python/issues?q=sort%3Aupdated-desc+is%3Aopen+label%3Ahacktoberfest) to see the valid issues.

# Rules and T&C.

- Only the person assigned by Team Crawlee will be considered a valid contributor
- You can also open new issues, but that has to be accepted by someone from Team Crawlee to be considered as a valid issue.
- Every contribution that is made between October 1, 2024, to October 31, 2024, in any time zone will be considered a valid contribution.
- We will allow you to complete the reviews or feedback our team gave until November 7, 2024.
- This activity is on a “first come first serve” basis.
- Any participant can get only one swag. No stacking of SWAG is allowed.
- The SWAG is in limited quantity.
- Not every contribution will be merged. Only contribution-matching standards can be merged; however, we will give the PR `hacktoberfest-accepted` label to count it as a contribution.
- For any query or support [join our discord server](https://apify.com/discord).

**Comment by Horlaitan15** [comment]
Hi, I'm not able to join the Discord channel and I would like to contribute to Crawlee. Came across it today. Thank you

**Comment by akshay11298** [comment]
Hi @souravjain540 , how do we get the swags? Is there some form or something that needs to be filled from our side?

**Comment by souravjain540** [comment]
Swag emails are sent! :)
