### ISSUE TITLE
What to do with the request query params field?

### ISSUE THREAD

**Issue by vdusek** [apify/crawlee-python#615]
- `Request.query_params`
- Our HTTP clients use it, Apify platform does not.
- See https://github.com/apify/crawlee-python/pull/542#discussion_r1813094025 for more information.

**Comment by janbuchar** [comment]
When it comes to sending the `Request` to the platform, the query params must be appended to the URL. Currently, we just drop the field in the SDK, which is not great.

How much of an inconvenience would it cause to just drop the field?
