### ISSUE TITLE
Add a custom URL type instead of rely on `httpx.URL`

### ISSUE THREAD

**Issue by vdusek** [apify/crawlee-python#630]
- We use the `httpx.URL` in the [ProxyConfiguration](https://github.com/apify/crawlee-python/blob/master/src/crawlee/proxy_configuration.py), in the tests and maybe in other places as well.
- It kind of shot us into the foot in #618.
- ~I suggest replacing it with our custom data type (either the Pydantic model or data class).~
    - As Honza said, we could probably utilize some 3rd party library, [yarl](https://pypi.org/project/yarl/) seems like a good option.
- Also please find other occurrences of the `httpx.URL` in the Crawlee and replace them with our custom type.
  - This applies also to tests: `httpbin: URL`
- Keep in mind, that URLs in the `Request` model need to be serialized as strings.

**Comment by janbuchar** [comment]
A Pydantic type wouldn't probably help us much, those are typically just for validation/serialization.

**Comment by janbuchar** [comment]
We might also want to use something like https://github.com/aio-libs/yarl

**Comment by vdusek** [comment]
@Mantisus

**Comment by janbuchar** [comment]
I experimented with `yarl` in #167 and found an issue - if you do `URL("https://some.tld/?asdf=hjkl") / "path"`, you lose the query string. This is unfortunate.

`httpx.URL` does not exhibit this behavior. I did not find any other usable (and maintained) URL-manipulation packages.

**Comment by Mantisus** [comment]
This is fixed in `yarl` 1.18.0, released today.

In this regard, I think `yarl` is optimal for this purpose

**Comment by vdusek** [comment]
The issue https://github.com/aio-libs/yarl/issues/111 is from 2017, and was resolved just a few hours ago, with a release that dropped 30 minutes ago. It feels like destiny.
