### ISSUE TITLE
Incompatibility with Type-Dependent Code:

### ISSUE THREAD

**Issue by anonymous-leviathan** [apify/crawlee-python#643]
If you have code that depends on evaluating types immediately—such as functions performing validation or conditional logic based on type hints—it will not work as expected with deferred annotations. The deferred annotations are only evaluated as strings, which may lead to subtle bugs if the code implicitly relies on immediate type evaluation.

path to file - ```crawlee-python/tree/master/src/crawlee/_utils/blocked.py```

**Comment by janbuchar** [comment]
The general argument is being discussed in https://github.com/apify/crawlee-python/issues/645. If you want to elaborate on this particular problem of deferred annotations, please do so here.
