### ISSUE TITLE
Runtime Type Inspection Limitations

### ISSUE THREAD

**Issue by anonymous-leviathan** [apify/crawlee-python#644]
Since type annotations are deferred to strings, any code or library that attempts to use annotations for runtime type inspection or dynamic behavior (like certain ORM libraries, or introspection tools) might fail, as they won’t see the actual types until they are explicitly evaluated. This can lead to unexpected behavior or errors if runtime access to type information is required.

path to file - ```https://github.com/apify/crawlee-python/tree/master/src/crawlee/_utils
/blocked.py```

**Comment by janbuchar** [comment]
The general argument is being discussed in https://github.com/apify/crawlee-python/issues/645. If you want to elaborate on this particular problem of deferred annotations, please do so here.
