### ISSUE TITLE
A helper function for simple HTML tag removal

### ISSUE THREAD

**Issue by janbuchar** [apify/crawlee-python#659]
See https://github.com/apify/crawlee/blob/master/packages/utils/src/internals/cheerio.ts#L42-L85 for inspiration.

The Python version should probably use `BeautifulSoup` and tell the user to install `crawlee[beautifulsoup]` if they try to use it without dependencies.

**Comment by Pijukatel** [comment]
I think that BS should already handle it using: `soup.get_text("\n", strip=True)`
https://www.crummy.com/software/BeautifulSoup/bs4/doc/#get-text . So maybe I should just wrap that in our utility function.
