### ISSUE TITLE
Export `HttpHeaders` from `crawlee`

### ISSUE THREAD

**Issue by tlinhart** [apify/crawlee-python#663]
I need to send a POST request to a site passing URL encoded form data. For that, I have to pass a `Content-Type` HTTP header with `application/x-www-form-urlencoded` value. In 0.4.0, I have to use a `HttpHeaders` model for `headers` parameter of `Request.from_url()` method to make type checker happy. However, this model is defined in `crawlee._types` module which seems to be a private module (at least that's the usual intent communicated with underscored module name). I guess it would be best if `HttpHeaders` was exported directly from a `crawlee` package.

**Comment by vdusek** [comment]
Hi, you are right, it should be exported, I'll fix it, thanks.
