### ISSUE TITLE
Integrate Camoufox into PlaywrightCrawler

### ISSUE THREAD

**Issue by Ehsan-U** [apify/crawlee-python#684]
crawlee-python is great but often lacks stealth against modern anti-bot measures when using vanilla playwright. 
[Camoufox](https://github.com/daijro/camoufox) is fully [compatible](https://camoufox.com/python/usage/) with playwright, only have to change browser initialization. It [bypasses](https://camoufox.com/stealth/) all currently available anti-bot measures. It would be a great opportunity to make crawlee-python playwright stealthy.

**Comment by janbuchar** [comment]
Hello @Ehsan-U, thank you for the suggestion, we will consider it!

**Comment by Pijukatel** [comment]
I tried two approaches:

**Tight integration into crawlee:**
https://github.com/apify/crawlee-python/pull/782
**Pros:**
- Super easy to use.
**Cons:**
- Does not give much flexibility in customizing the Camoufox behavior. (Like turning off crawlee header generation and use Camoufox header generation)
- Additional dependency for crawlee (currently does not install on Python3.13)


**No integration, but creating example code that shows how to do it with current codebase:**
https://github.com/apify/crawlee-python/pull/789
**Pros:**
- No extra dependency for crawlee
- No need to modify existing code
- Big flexibility
**Cons**
-Not as easy to use as the first approach. But still straightforward with the example.

**Comment by Ehsan-U** [comment]
It would be fantastic for Crawlee to introduce a plugin system similar to what Scrapy offers. For example, here's a plugin I developed for Camoufox that integrates seamlessly with Scrapy: [scrapy-camoufox](https://github.com/Ehsan-U/scrapy-camoufox). This approach proves highly effective, as it extends functionality without requiring any changes to Scrapy's core.

**Comment by MarhyCZ** [comment]
Hey @Ehsan-U I stumbled upon your thread. I wanted to look into scrapy-camoufox. Have you taken the repo offline?

**Comment by Ehsan-U** [comment]
> Hey @Ehsan-U I stumbled upon your thread. I wanted to look into scrapy-camoufox. Have you taken the repo offline?

Hi @MarhyCZ, Thanks for showing interest ! here is the repo: https://github.com/Ehsan-U/scrapy-camoufox

**Comment by murilomulato** [comment]
Hey @Ehsan-U I wanted to look into scrapy-camoufox. Have you taken the repo offline?
