### ISSUE TITLE
Expose the `browser_options` to the PlaywrightCrawler

### ISSUE THREAD

**Issue by vdusek** [apify/crawlee-python#719]
- In the same way as we do it for `headless` and `broser_type`.
- https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch
- Also improve arg docs, add links to the PW docs

**Comment by Mantisus** [comment]
It seems to me that in `PlaywrightBrowserPlugin`[https://crawlee.dev/python/api/class/PlaywrightBrowserPlugin] documentation it is enough to specify that `browser_options` supports all parameters supported by `Playwright launch`[https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch].

Now it is not clear without looking at the source code. But adding all parameters to `PlaywrightCrawler` looks like an overhead to me.
