### ISSUE TITLE
autoscaled_pool.desired_concurrency_ratio is useless

### ISSUE THREAD

**Issue by Pijukatel** [apify/crawlee-python#759]
It seems to me that autoscaled_pool.desired_concurrency_ratio is currently completely useless.

It is in init here:
https://github.com/apify/crawlee-python/blob/master/src/crawlee/_autoscaling/autoscaled_pool.py#L57

It is checked for bounds 0> desired_concurrency_ratio >=1
https://github.com/apify/crawlee-python/blob/master/src/crawlee/_autoscaling/autoscaled_pool.py#L97

It is used in only one place:
https://github.com/apify/crawlee-python/blob/master/src/crawlee/_autoscaling/autoscaled_pool.py#L198

And from there in condition here:
https://github.com/apify/crawlee-python/blob/master/src/crawlee/_autoscaling/autoscaled_pool.py#L202

That condition will **always be true for** currently runtime enforced values  **0> desired_concurrency_ratio >=1**:

self.current_concurrency >= math.floor(**self._desired_concurrency_ratio** * self.current_concurrency)

Did I miss something?

**Comment by janbuchar** [comment]
Before we look deeper into this, did you cross-check this against the JS version? Does it do the same thing there?

**Comment by Pijukatel** [comment]
I think it is exactly the same

[        const minCurrentConcurrency = Math.floor(this._desiredConcurrency * this.desiredConcurrencyRatio);](https://github.com/apify/crawlee/blob/30d0bf807f110b2bacf74d8099e9565edb509df7/packages/core/src/autoscaling/autoscaled_pool.ts#L597)

**Comment by vikyw89** [comment]
In js concurrency setting works, in here it doesn't

**Comment by Pijukatel** [comment]
Yes, in JS it is different. I read it incorrectly earlier. So it seems like there was a mistake when porting the code to Python.

JS:
const minCurrentConcurrency = Math.floor(**this._desiredConcurrency** * this.desiredConcurrencyRatio);

Python:
min_current_concurrency = math.floor(self._desired_concurrency_ratio * **self.current_concurrency**)

**Comment by Pijukatel** [comment]
Yes, I will align the Python version with the JS version.
