### ISSUE TITLE
Implement fingerprinting

### ISSUE THREAD

**Issue by vdusek** [apify/crawlee-python#80]
Coordinate with @barjin before implementing anything.

There is a possibility of developing a dedicated fingerprinting library (in Rust?). In that case, we will do just some wrapping in Python tooling (same in JavaScript).

**Comment by Mantisus** [comment]
Hey

This may be useful to you.

There is a project - https://github.com/FlorianREGAZ/Python-Tls-Client
which is a Python wrapper around the Golang library - 
https://github.com/bogdanfinn/tls-client

The disadvantage of python-tls is that it doesn't implement asynchrony. So this project is not suitable for crawlee-python at this stage.

But you might consider implementing your wrapper for https://github.com/bogdanfinn/tls-client.

**Comment by vdusek** [comment]
Closing this one, as its content was divided into several smaller issues: #292, #401, #402.
