### ISSUE TITLE
Unable to stop crawler. Facing error: "'PlaywrightCrawler' object has no attribute 'stop'"

### ISSUE THREAD

**Issue by abhichek** [apify/crawlee-python#832]
### Description
While using the Python SDK of Crawlee with PlaywrightCrawler, I encountered an issue where the `stop()` method mentioned in the documentation is not available. This is particularly problematic when trying to implement custom crawling logic that requires programmatic stopping of the crawler.

When attempting to call `pw_crawler.stop()` from within the request handler, I receive the error:

`AttributeError: 'PlaywrightCrawler' object has no attribute 'stop'`

### Expected Behavior
According to the documentation, we should be able to call `crawler.stop()` to gracefully terminate the crawling process. This is especially important when implementing custom logic like:
- Stopping after processing specific content types
- Handling custom request limits
- Managing crawler state based on business logic

### Current Behavior
The Python implementation of PlaywrightCrawler doesn't expose the `stop()` method, making it impossible to programmatically stop the crawler from within async request handlers or navigation hooks.

### Impact
Without a proper stop mechanism, developers are forced to:
- Raise exceptions to terminate crawling (which feels hacky)
- Implement complex state management
- Cannot gracefully stop the crawler while preserving the crawled data
- Risk potential memory leaks or resource management issues

### Environment
- Crawlee Python: 3.11
- Python Version: 3.11
- Platform: Linux/Docker

### Additional Context
This is critical for production environments where we need precise control over the crawling process, especially when:
- Implementing custom request limits
- Handling mixed content types (web pages and files)
- Managing crawler resources in containerized environments
- Implementing graceful shutdown mechanisms

Would appreciate clarification on the recommended approach for programmatically stopping the crawler in the Python SDK.

**Comment by janbuchar** [comment]
Hi @abhichek and thank you for your interest in Crawlee! This feature is not yet released - see the [changelog](https://crawlee.dev/python/docs/changelog). If you want to test this before 0.5 is released, you can install a beta - https://pypi.org/project/crawlee/0.5.0b21/

**Comment by abhichek** [comment]
Hey @janbuchar , thanks for the response! The beta version looks promising, but for production environments we need the stable release. Could you share an estimated timeline for when version 0.5 will be released? 

Also, is there a recommended approach for gracefully stopping the crawler in the current stable version? We're seeing some edge cases where Crawlee's internal request counter and our custom counter get out of sync, and a proper stop mechanism would help us manage this better.

Thanks.

**Comment by janbuchar** [comment]
Hi @abhichek, we will probably release 0.5 in the first days of 2025 - most of us will not be available during Christmas to provide support and hotfix any possible bugs.

That aside, crawlee-python still hasn't reached 1.0, so calling it stable is a bit of an overstatement. We're happy that you are using it nevertheless :slightly_smiling_face:
