### ISSUE TITLE
Tiered proxy urls doesn't allow None as in docs

### ISSUE THREAD

**Issue by Rigos0** [apify/crawlee-python#846]
Hi,

The documentation here: https://crawlee.dev/python/docs/guides/proxy-management# shows an example which uses None for the proxy lowest tier if we don't want to use a proxy. The issue is when I tried this setting in my scraper, it does not pass the validator checks as it is looking for _AnyHttpUrl_ :  
![image](https://github.com/user-attachments/assets/8da1e3a8-eb45-45b3-a15c-e4179d5c14ab)

**Comment by Mantisus** [comment]
Hey @Rigos0

This will work from version 0.5.0, you can test it on version 0.5.0b30

Documentation is updated when PR is merged into master branch. This is the reason for this confusion
